sudo: required
dist: trusty
services: docker

env: DOCKER=centos

before_install:
  - sed -i -e "s#@@AAL2_RPM@@#$AAL2_RPM#" .travis_Dockerfile

install:
  - docker build -t vacman_controller -f .travis_Dockerfile .

script:
  - docker run -t vacman_controller
