sudo: required
dist: trusty
services: docker

env:
  - DOCKER=centos
  - CC_TEST_REPORTER_ID=47866d6bec01d504297b03fb6b387103da34b1ac72a7bad784eaf52d85fc7bf8

install:
  - docker build -t vacman_controller -f .travis_Dockerfile .

before_script:
  - sh -x .travis_prepare_environment.sh

script:
  - docker run --interactive --tty --env-file .travis_env vacman_controller
