sudo: required
dist: trusty
services: docker

env:
  - DOCKER=centos
  - CC_TEST_REPORTER_ID=47866d6bec01d504297b03fb6b387103da34b1ac72a7bad784eaf52d85fc7bf8

before_install:
  - sh -x .travis_prepare_Dockerfile.sh

install:
  - docker build -t vacman_controller -f .travis_Dockerfile .

script:
  - docker run -t vacman_controller
