require 'vacman_controller/vacman_controller'

# Provides VACMAN Controller functionality to identify and authorize user via VASCO DIGIPASS tokens.
#
#
module VacmanController
  extend self

  # Import .dpx file containing the secure token-data
  #
  # == Parameters:
  # filename::
  #   The path of the .dpx file to load
  # key::
  #   The secure key to decrypt the dpx file
  #
  # == Returns:
  # A list of hashes. Each hash contains
  #   serial: the serial number of the token
  #   blob:   the blob containing some secret magic data
  #   app_name: the application name (the security method)
  #   flags1: some flags
  #   flags2: more flags
  #
  # this hash must be persisted and regained for each call of verify_password and generate_password
  #
  def import(filename, key)
    VacmanLowLevel.import(filename, key)
  end



  # Generate a Password for a user. This does the same as hitting the button on your hardware token
  #
  # == Parameters:
  # hash::
  #   The hash for a specific token (you get these in import)
  #
  # == Returns:
  # The password string. The password is only valid for a period (todo: add method to change the period, currently its 30 seconds)
  #
  def generate_password(hash)
    VacmanLowLevel.generate_password(hash)
  end



  # Verify a password. This is the usecase a user sends you a password generated by his token and we have to verify it.
  #
  # == Parameters:
  # hash::
  #   The hash for a specific token (you get these in import)
  # pw::
  #   The password provided by the user
  #
  # == Returns:
  # true if the password is valid, false otherwise
  #
  # ATTENTION: it is very important to persist the hash afterwards!!!
  #
  def verify_password(hash, pw)
    VacmanLowLevel.verify_password(hash, pw)
  end



  # Gets the available kernel property names
  #
  def kernel_property_names
    @_kernel_property_names ||= VacmanLowLevel.kernel_property_names
  end



  # Get a kernel parameter, wich is a basically a setting for vacman controller
  #
  # == Parameters:
  # name::
  #   the param name. Most TKernelParms struct elements are accessible.
  #
  def get_kernel_param(name)
    VacmanLowLevel.get_kernel_param(name)
  end



  # Change a kernel parameter, wich is a basically a setting for vacman controller
  #
  # == Parameters:
  # name::
  #   the param name. Most TKernelParms struct elements are accessible.
  # val::
  #   the fixnum value
  #
  def set_kernel_param(name, val)
    VacmanLowLevel.set_kernel_param(name, val)
  end



  # Returns all configured kernel parameters
  #
  def get_kernel_all_parameters
    kernel_property_names.inject({}) do |h, name|
      h.update(name => (get_kernel_param(name) rescue "ERROR: #$!"))
    end
  end



  # Gets the available token property names
  #
  def token_property_names
    @_token_property_names ||= VacmanLowLevel.token_property_names
  end



  # Get a token single property
  #
  # == Parameters:
  # hash::
  #   the hash for a specific token (you get these in import)
  # property::
  #   the property name. See +token_property_names+
  #
  def get_token_property(hash, property)
    VacmanLowLevel.get_token_property(hash, property)
  end



  # Set a token single property
  #
  # == Parameters:
  # hash::
  #   the hash for a specific token (you get these in import)
  # property::
  #   the property name. See +token_property_names+
  # value::
  #   the property value. Only values convertible to integer are supported.
  #
  # possible names:
  #
  #
  def set_token_property(hash, property, value)
    VacmanLowLevel.set_token_property(hash, property, value)
  end



  # Returns all properties configured for a token
  #
  def get_token_all_properties(hash)
    token_property_names.inject({}) do |h, name|
      h.update(name => (get_token_property(hash, name) rescue "ERROR: #$!"))
    end
  end
end
